-- Supabase SQL schema for Cypherdon MVP

-- 1. Users Table (Extends Supabase Auth users)
CREATE TABLE public.users (
    id UUID REFERENCES auth.users(id) NOT NULL PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    skills TEXT[] DEFAULT '{}',
    experience_level TEXT DEFAULT 'entry',
    resume_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure RLS is enabled if desired
-- ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 2. Jobs Table (Scraped data)
CREATE TABLE public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title TEXT NOT NULL,
    description TEXT NOT NULL,
    location TEXT,
    apply_link TEXT NOT NULL,
    company_name TEXT,
    match_score INT, -- optional storage
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Applications Table (User -> Job application state)
CREATE TABLE public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) NOT NULL,
    job_id BIGINT REFERENCES public.jobs(id) NOT NULL,
    match_score INTEGER,
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending_captcha', 'completed', 'failed'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
